[package]
name = "cdump-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
darling.workspace = true
libc.workspace = true

[lib]
proc-macro = true
